apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mtfl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mtfl
    app.kubernetes.io/part-of: tkrw-pr714-0075-0008-app
  name: devfile-sample-mtfl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mtfl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mtfl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0008-tenant/tkrw-pr714-0075-0008-app/devfile-sample-mtfl@sha256:ac65c89554dbb79abfcfd4e713bc59f4afa2de966fd3fb07e3994131caa5c346
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
